from typing import Annotated, TypedDict, List, Dict, Any
from langgraph.graph.message import add_messages


class SchedulerState(TypedDict):
    """
    Shared memory for the weekly scheduling agent graph.

    The 'messages' field uses the add_messages reducer, which APPENDS
    new messages instead of overwriting. This gives the LLM full context
    of previous drafts, critiques, and tool calls across loop iterations.
    All other fields use the default reducer (last-write-wins).
    """

    # The initial, unstructured input from the user
    raw_tasks: str

    # The user's current location / home base (e.g. "123 Main St, Austin, TX")
    user_location: str

    # IANA timezone derived from user_location (e.g. "Europe/Bucharest")
    user_timezone: str

    # Text extracted from uploaded documents (images, PDFs, .txt files)
    uploaded_files_text: str

    # Structured list of tasks after the AI processes them
    # Each task may include: task, duration, priority, deadline, location,
    # preferred_day (str|null), is_recurring (bool), recurrence_days (list),
    # date_deadline (str|null "YYYY-MM-DD"), goal_id (int|null)
    parsed_tasks: List[Dict[str, Any]]

    # The readable text version of the weekly plan
    draft_schedule: str

    # JSON-structured weekly schedule: dict keyed by day name
    # e.g. {"Monday": [...entries...], "Tuesday": [...], ...}
    structured_schedule: Dict[str, Any]

    # The feedback generated by the Critic node (or user tweaks)
    critique: str

    # Loop counter to prevent infinite revision cycles
    revision_count: int

    # Conversation history: uses add_messages reducer so entries accumulate
    # across loops, giving the LLM full context of prior attempts
    messages: Annotated[list, add_messages]

    # Stores the human's response during the HITL interrupt
    human_feedback: str

    # 1-3 weekly macro-goals (e.g. ["Finish Physics Project", "Gym 3x"])
    macro_goals: List[str]

    # Fixed recurring tasks loaded from a saved template (e.g. university classes)
    # These are pre-parsed task dicts injected before the task_ingester runs.
    template_tasks: List[Dict[str, Any]]

    # Weekly goal chunks generated by the goal_decomposer node.
    # Each is a task dict with goal metadata (goal_db_id, goal_name, etc.)
    goal_chunks: List[Dict[str, Any]]


class RescheduleState(TypedDict):
    """
    State for the dynamic rescheduler graph — triggered when the user
    clicks "I'm Behind". Produces a compressed rest-of-day schedule.
    """

    # Current time as HH:MM string
    current_time: str

    # User's IANA timezone
    user_timezone: str

    # User's location for context
    user_location: str

    # Today's day name (e.g. "Monday")
    today_name: str

    # Tomorrow's day name (e.g. "Tuesday")
    tomorrow_name: str

    # Remaining unchecked tasks for today (list of schedule entry dicts)
    remaining_tasks: List[Dict[str, Any]]

    # Tomorrow's current schedule entries
    tomorrow_schedule: List[Dict[str, Any]]

    # All parsed tasks (for priority reference)
    parsed_tasks: List[Dict[str, Any]]

    # Output: rescheduled rest-of-today entries
    rescheduled_today: List[Dict[str, Any]]

    # Output: updated tomorrow entries (low-priority tasks pushed here)
    rescheduled_tomorrow: List[Dict[str, Any]]

    # Conversation log
    messages: Annotated[list, add_messages]
