from typing import Annotated, TypedDict, List, Dict, Any
from langgraph.graph.message import add_messages


class SchedulerState(TypedDict):
    """
    Shared memory for the scheduling agent graph.

    The 'messages' field uses the add_messages reducer, which APPENDS
    new messages instead of overwriting. This gives the LLM full context
    of previous drafts, critiques, and tool calls across loop iterations.
    All other fields use the default reducer (last-write-wins).
    """

    # The initial, unstructured input from the user
    raw_tasks: str

    # The user's current location / home base (e.g. "123 Main St, Austin, TX")
    user_location: str

    # IANA timezone derived from user_location (e.g. "Europe/Bucharest")
    user_timezone: str

    # Text extracted from uploaded documents (images, PDFs, .txt files)
    uploaded_files_text: str

    # Structured list of tasks after the AI processes them
    parsed_tasks: List[Dict[str, Any]]

    # The chronological day plan generated by the Scheduler node
    draft_schedule: str

    # JSON-structured version of the schedule for rich UI rendering
    structured_schedule: List[Dict[str, Any]]

    # The feedback generated by the Critic node (or user tweaks)
    critique: str

    # Loop counter to prevent infinite revision cycles
    revision_count: int

    # Conversation history: uses add_messages reducer so entries accumulate
    # across loops, giving the LLM full context of prior attempts
    messages: Annotated[list, add_messages]

    # Stores the human's response during the HITL interrupt
    human_feedback: str
